AWSTemplateFormatVersion: '2010-09-09'
Transform: "AWS::Serverless-2016-10-31"

Description: >
  Amazon Polly Builder Demo Template [Local]. PLEASE USE A UNIQUE STACK NAME IF YOU ARE ALREADY RUNNING THIS TEMPLATE. This template will create the Amazon API Gateway + associated AWS Lambda Function.

Resources:
  ApiFunctionExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/CloudWatchLogsFullAccess
        - arn:aws:iam::aws:policy/AmazonPollyFullAccess

  ApiFunction:
    Type: AWS::Lambda::Function
    Properties:
      Code:
        S3Bucket: "amazon-polly-demo"
        S3Key: "Amazon-Polly-Builder-PollyLambda.zip"
      FunctionName: !Sub 'AIServicesDemo-PollyBuilder-${AWS::StackName}-ApiHandler'
      Handler: lambda_function.lambda_handler
      MemorySize: 128
      Role: !GetAtt ApiFunctionExecutionRole.Arn
      Runtime: python2.7
      Timeout: 30

  Api:
    Type: AWS::ApiGatewayV2::Api
    Properties:
      CorsConfiguration:
        AllowHeaders:
          - '*'
        AllowMethods:
          - '*'
        AllowOrigins:
          - '*'
      Name: AIServicesDemo-Amazon-Polly-Api
      ProtocolType: HTTP
      Target: !GetAtt ApiFunction.Arn

  ApiPermission:
    Type: AWS::Lambda::Permission
    Properties:
      Action: lambda:InvokeFunction
      FunctionName: !Ref ApiFunction
      Principal: apigateway.amazonaws.com

Outputs:
  ApiEndpoint:
    Description: The API endpoint
    Value: !Sub 'https://${Api}.execute-api.${AWS::Region}.amazonaws.com'