AWSTemplateFormatVersion: '2010-09-09'
Transform: "AWS::Serverless-2016-10-31"

Description: >
  Amazon Translate Sentiments Template [Local]. PLEASE USE A UNIQUE STACK NAME IF YOU ARE ALREADY RUNNING THIS TEMPLATE. This template will create the Amazon API Gateway + associated AWS Lambda Function.
Resources:
  ApiFunctionExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: WriteCloudWatchLogsLocal
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action:
                  - 'logs:CreateLogGroup'
                  - 'logs:CreateLogStream'
                  - 'logs:PutLogEvents'
                Resource: 'arn:aws:logs:*:*:*'
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/TranslateFullAccess
        - arn:aws:iam::aws:policy/ComprehendFullAccess

  ApiFunction:
    Type: AWS::Lambda::Function
    Properties:
      Code:
        S3Bucket: "aidemos-translatesentiments"
        S3Key: "aidemos-translatesentiments-lambda.zip"
      FunctionName: !Sub 'AIDemos-TranslateSentiments-${AWS::StackName}-ApiHandler'
      Handler: lambda_function.lambda_handler
      MemorySize: 128
      Role: !GetAtt ApiFunctionExecutionRole.Arn
      Runtime: python3.8
      Timeout: 30

  Api:
    Type: AWS::ApiGatewayV2::Api
    Properties:
      CorsConfiguration:
        AllowHeaders:
          - '*'
        AllowMethods:
          - '*'
        AllowOrigins:
          - '*'
      Name: AIDemos-TranslateSentiments-API
      ProtocolType: HTTP
      Target: !GetAtt ApiFunction.Arn

  ApiPermission:
    Type: AWS::Lambda::Permission
    Properties:
      Action: lambda:InvokeFunction
      FunctionName: !Ref ApiFunction
      Principal: apigateway.amazonaws.com

Outputs:
  ApiEndpoint:
    Description: The API endpoint
    Value: !Sub 'https://${Api}.execute-api.${AWS::Region}.amazonaws.com'